# Bootloader selection
BOOTLOADER = rp2040

SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor

ENCODER_ENABLE = yes

# OLED_ENABLE = yes
# OLED_TRANSPORT = i2c

# OS_DETECTION_ENABLE = yes

CONSOLE_ENABLE = yes